### PR TITLE
Update zh-Hans.hjson

### PR DESCRIPTION
**Pull request by sjzd123456**
by 906170601

### CODE REVIEW

**Comment by direwolf420** [comment]
Thanks for the PR, I will have someone proofread it and report back soon.

**Comment by direwolf420** [comment]
@sjzd123456 hey, here's a list of things that can be improved:

`ItemMagnetBuff.Description: "A"` doesn't have to correspond to "一个", we mostly don't include number words in that case.
"Custom Item *Filter*", "过滤器" is weird (usually for physically filtering or metaphor), "筛选" sounds better.
"Magnet Behavior (Only works ingame)" ->  "仅在世界中有效/仅在进入世界后有效", because "游戏中" means in the technical game, not 'playing in a world'
"Resulting Magnet Stats" is not "生成的磁铁统计" (generated magnet statistics), "磁铁数据总计" maybe
"*Toggle* if hearts should be picked up by the magnet", the "Toggle" should not be "切换", I'd omit it since "是否" already says "if yes or no"
The same for all "Toggle"s
"Mana" is "魔力", as the official lanaguage pack chose so
"Coin" is not "金币" (gold coin), use "钱币"
"Pickup *Effect* Items", "效果" is pretty vague and ambiguous, use "特效" (special effect (of something))
"Toggle if items like nebula armor boosters or modded items like the music notes from Thorium should be picked up by the magnet" "磁铁是否吸取星云强化焰和瑟银模组的音符之类的物品", Thorium refers to the mod of the same name (Thorium Mod), which has an item called "music note". "nebula armor boosters" is this: <https://terraria.wiki.gg/zh/wiki/%E6%98%9F%E4%BA%91%E7%9B%94%E7%94%B2>

**Comment by sjzd123456** [comment]
OK,I have update.

**Comment by direwolf420** [comment]
@sjzd123456 Thanks! Here's the final set of adjustments, after this is addressed I will merge it. What name do you want to be credited as? "906170601"?

"List Mode Toggle" — "筛选列表" (filter lists), "选择物品筛选列表" (choose item filter list)
"Held" — "手持" (held in hand), "……（而非在背包中即可）",  "持有" (held) means "have something", not neccesarily "held in hand"
it translates "inventory" to "物品栏", which can mean "item slots" or the hot bar, so I would use "背包" (backpack, here stands for the inventory)
same for NeedsSpace tooltip
"Instant" — "瞬移" ("teleport" or "move in an instant"), "被吸取的物品是否瞬移 —— 无视速度或加速度，但仍受范围限制"
"Range" — tooltip: "以格为单位的基础半径", the "格" here is "grid", means a tile as a grid, the original "瓷砖" is the tile to cover our bathroom floor&wall
all those `CurrentXXX` labels should: "生成的" (generated) → "最终" (final)
"Increase With Bosses" — "随 Boss 进度增加" (increases with boss progress)
Acceleration — tooltip: "物品多快加到最高速度"

**Comment by sjzd123456** [comment]
Both names are fine, one is my GitHub username, the other is my Steam username. Besides, I have made update as required and submitted, please check.

**Comment by direwolf420** [comment]
Thanks a lot, this translation now fits the game alot more than the first iteration. I will publish this update in the coming days, and credit you as `906170601`.

**Pull request merged**
